name: Build
env:
  CI: true
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform base checks
        run: ./gradlew assembleDebug
  KTLINT_CHECK:
    name: ktlint quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform ktlint
        run: ./gradlew ktlint
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute unit tests
        run: ./gradlew testDebugUnitTest
      - name: Upload unit tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: unit_tests
          path: ./app/build/jacoco/
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [26, 27, 28, 29]
        include:
          - EMULATOR_API: 29
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 28
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 27
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 26
            EMULATOR_ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.2.0
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated -camera-front emulated -gpu swiftshader_indirect
          emulator-build: 6110076
          script: ./gradlew connectedCheck
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          path: ./app/build/outputs/code_coverage/debugAndroidTest/connected
  CODE_COVERAGE:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [ANDROID_UNIT_TESTS, ANDROID_EMULATOR_TESTS]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download unit tests artifact
        uses: actions/download-artifact@v1
        with:
          name: unit_tests
          path: ./app/build/jacoco/
      - name: Download emulator tests artifact
        uses: actions/download-artifact@v1
        with:
          # 27 is the EMULATOR_API with less SdkExclude annotations, and should have the best possible coverage.
          name: emulator_tests_27
          path: ./app/build/outputs/code_coverage/debugAndroidTest/connected
      - name: Create merged coverage report
        run: ./gradlew mergeCoverageReports
      - name: Upload merged coverage report (GitHub)
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: ./app/build/reports/mergedCoverageReport
      - name: Upload merged coverage report (Codecov)
        uses: codecov/codecov-action@v1
        with:
          file: ./app/build/reports/mergedCoverageReport/*
          fail_ci_if_error: true